### ISSUE TITLE
Comment count bugs

### ISSUE THREAD

**Issue by marquestye** [mcmc101001/Orbital2023#201]
When new comment is posted, resource paper comment count does not update even after refresh.

**Comment by marquestye** [comment]
Shows deleted comment even though reply has been deleted (Steps to recreate: delete comment, then delete reply)

**Comment by marquestye** [comment]
Comment count does not decrease after deleteing comment in solution comments.

**Comment by mcmc101001** [comment]
Removed comment count. Quite ambiguous if we shld include deleted comments or replies as well

**Comment by mcmc101001** [comment]
reopening this to try and fix
