### ISSUE TITLE
Runtime error when toggling to PYP resource

### ISSUE THREAD

**Issue by marquestye** [mcmc101001/Orbital2023#74]
![image](https://github.com/mcmc101001/Orbital2023/assets/97437396/45e40864-ca68-4c0d-b529-584807faceba)

**Comment by mcmc101001** [comment]
can try and pull code to see your prisma schema has the field difficulties (in bold below)

model QuestionPaper {
  id            String                    @id @default(cuid())
  name          String
  createdAt     DateTime                  @default(now())
  userSubmitted User                      @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId        String
  moduleCode    String
  acadYear      String
  semester      String
  type          ExamType
  votes         QuestionPaperVote[]
  **difficulties  QuestionPaperDifficulty[]**

  @@index([userId])
}

if not see if you are using the same database as me (the remote link we shared)

**Comment by marquestye** [comment]
Schema is identical. Database should be the same since I can view the cheatsheets and notes we previously uploaded.

**Comment by mcmc101001** [comment]
Check if using the latest version, which has the code as 

<img width="241" alt="image" src="https://github.com/mcmc101001/Orbital2023/assets/96778937/956497f2-0bee-4298-a1b6-5d5d10c96842">

It should be as such, where the count does not include votes

**Comment by mcmc101001** [comment]
fixed by running npx prisma db push again, as there was schema mismatch in the client side prisma file when schema was not pushed
