### ISSUE TITLE
Custom PDF viewer

### ISSUE THREAD

**Issue by mcmc101001** [mcmc101001/Orbital2023#99]
Currently using iframe to view pdf. Can consider building our custom pdf viewer, which could have the following features:

1. zoom
1. annotate?
1. download
1. custom scrollbar
1. fullscreen

**Comment by marquestye** [comment]
![image](https://github.com/mcmc101001/Orbital2023/assets/97437396/50267591-2f45-46fe-991d-8e84caf06fc5)
Ran into issue with react-pdf, turns out it works for older nextjs directory system pages/index but not for newer app/page

**Comment by mcmc101001** [comment]
we have fixed iframe to not rerender on refresh so it shld be good
